export interface TableColumn {
  label: string
  key: number | string
  ui?: string
  stickyRight?: boolean
}
export const OrderColumn = [
  { label: 'Order ID', key: 'order_id' },
  { label: 'Seller SKU', key: 'seller_sku' },
  { label: 'Product Name', key: 'product_name' },
  { label: 'Variation', key: 'variation' },
  { label: 'Quantity', key: 'quantity' },
  { label: 'Created Time', key: 'created_time' },
  { label: 'Buyer Message', key: 'buyer_message' },
  { label: 'Buyer Name', key: 'buyer_name' },
  { label: 'Assigne', key: 'assign_for' },
  { label: 'Actions', key: 'actions', stickyRight: true },
]

export const EmployeeColumn = [
  { label: 'ID', key: 'id' },
  {
    label: 'Name',
    key: 'name',
  },
  {
    label: 'Gender',
    key: 'gender',
  },
  {
    label: 'Date of Birth',
    key: 'date_of_birth',
  },
  {
    label: 'Phone',
    key: 'phone',
  },
  {
    label: 'Address',
    key: 'address',
  },
  {
    label: 'Status',
    key: 'status',
  },
  // { label: '' },
  { label: 'Actions', key: 'actions', stickyRight: true },
]
export const tempE = [
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
  {
    id: 1,
    name: 'Jeffpham',
    gender: 'Male',
    date_of_birth: '29/06/2002',
    phone: '0327016348',
    address: '292 Kim giang, Đại Kim, Hoàng Mai, Hà Nội',
    status: 'Active',
  },
]
